### ISSUE TITLE
question about nn.InstanceNorm2d！

### ISSUE THREAD

**Issue by ioyy900205** [YoshikiMas/speech-enhancement-with-pytorch-lightning#2]
Thanks to the author for providing the code, which gave me a great convenience in my research. One question I have is why use nn.InstanceNorm2d instead of BN . Have the authors done any relevant comparison experiments?

**Comment by YoshikiMas** [comment]
We look forward to helping you! There is no reason to be particular about instance normalization (IN). I did not compare IN with BN or other normalization layers.
